/* Bilingual prototype resources and authored synthetic document fixtures.
   User-authored document text stays verbatim when the interface language changes. */
const copy = {
  zh: {
    designTitle:'Knowledge 界面',prototype:'设计提案 · 示例数据',scenario:'预览场景',theme:'切换外观',language:'切换界面语言',reset:'重置',notes:'设计说明',
    populated:'资料浏览',emptyScenario:'空资料库',citationScenario:'历史引用',failureScenario:'导入失败',navigation:'Mira 导航',toggleSidebar:'显示或隐藏侧栏',
    newConversation:'新对话',memory:'记忆',knowledge:'知识库',tasks:'任务',workspaces:'工作区',inbox:'收件箱',recentConversations:'最近对话',settings:'设置',
    import:'导入资料',sourceList:'资料列表',sourcePreview:'资料预览',search:'搜索标题或正文',scopeFilter:'筛选范围',statusFilter:'筛选状态',sort:'排序',allScopes:'全部范围',allStatuses:'全部状态',ready:'可检索',localOnly:'仅本地',modelUse:'可供模型使用',failed:'解析失败',needsAttention:'需要处理',updateFailed:'更新失败',versionTotal:n=>`${n} 个版本`,recent:'最近更新',titleSort:'按标题',count:n=>`${n} 份资料`,hits:n=>`${n} 份匹配资料`,localSnapshots:'资料副本保存在此设备',
    document:'正文',versions:'版本',information:'资料信息',current:'当前',historical:'历史',version:n=>`版本 ${n}`,currentVersion:n=>`版本 ${n} · 当前`,versionLabel:'选择资料版本',updated:'更新于',imported:'导入于',markdown:'Markdown',readOriginal:'查看原文',readPreview:'阅读预览',back:'返回资料',close:'关闭',cancel:'取消',done:'完成',more:'更多操作',update:'更新资料',delete:'删除资料',permission:'模型使用权限',changePermission:'更改权限',
    emptyTitle:'把有用的资料放在一起',emptyBody:'导入 Markdown，随时阅读；允许模型使用后，可在对话中检索和引用。',selectSource:'选择一份资料，开始阅读',noResults:'没有找到相关资料',noResultsBody:'试试其他关键词，或调整范围与状态。',clearFilters:'清除筛选',
    snapshotHint:'已导入的快照 · 原文件不会自动同步',historicalNotice:'正在查看历史版本。新的对话检索使用当前版本。',backCurrent:'返回当前版本',citationNotice:'这段回答引用了版本 1 的第 14–16 行。资料更新后，引用仍指向当时的原文。',citationUnavailable:'这条引用已不可用',citationUnavailableBody:'资料已删除或模型使用权限已撤销。这里不再显示引用正文。',citationTitle:'对话中的引用',citationConversation:'首版的功能边界',citationQuestion:'首版支持哪些资料格式？',citationAnswer:'首版支持导入 Markdown，并保留资料快照。PDF 和网页快照放在后续版本。',openCitation:'查看引用原文',
    versionsHelp:'每次明确更新都会保留一个版本。已有回答的引用不会改指向新内容。',view:'查看',successfulUpdate:'资料更新成功',firstImport:'首次导入',failedUpdate:'更新未成功 · 继续使用此前版本',historyUnchanged:'历史版本保留，不支持在此恢复为当前版本。',
    scope:'所属范围',file:'原始文件',size:'文件大小',parseState:'解析状态',versionCount:'保留版本',sourceType:'资料类型',snapshot:'导入快照',fileAccess:'导入后不再访问原文件；修改原文件不会影响此副本。',localDescription:'可在此设备阅读和搜索。不会用于远程模型请求。',remoteDescription:'相关内容可用于此范围内的对话，并发送给当前获准使用的模型服务商。',
    importTitle:'导入 Markdown 资料',importIntro:'保存一份可检索的本地快照。原文件不会被修改，也不会自动同步。',chooseSamples:'选择示例文件',dropHint:'选择一个或多个 Markdown 文件',formatHint:'.md / .markdown · 每份最多 10 MB · 每批最多 100 份',importScope:'导入到',allowRemote:'允许模型在对话中使用',allowRemoteHelp:'开启后，相关片段可能发送给已配置并获准使用的模型服务商。默认仅本地。',startImport:'导入 3 份资料',importing:'正在导入…',sampleHelp:'此设计稿使用内置示例，不读取你的文件。',importResultTitle:'导入完成',importResultIntro:'1 份已导入，1 份已存在，1 份需要处理。',added:'已导入',duplicate:'已存在',duplicateHelp:'相同范围与内容，已复用现有资料。',encodingError:'文件不是有效的 UTF-8 文本。请另存为 UTF-8 后重新导入。',viewImported:'查看已导入资料',retry:'重新选择文件',sampleNew:'阅读方法.md',sampleDuplicate:'Mira 产品原则.md',sampleBad:'访谈记录.md',importToast:'资料已导入，默认仅在本地使用。',
    updateTitle:'更新这份资料',updateIntro:'选择新版 Markdown。更新成功后用于检索；旧版本及其引用会保留。',updateName:'资料名称和所属范围保持不变。',chooseUpdate:'选择新版示例',updateSuccess:'有效的新版本',updateFailure:'模拟编码错误',confirmUpdate:'更新资料',updateToast:'新版本已保存，旧引用保持不变。',updateFailedToast:'更新未成功，当前版本保持不变。',failedBody:'原始文件已保留，但无法解析为可检索的正文。',failedNoCurrent:'暂无可用正文',failedCurrent:'此次更新解析失败。检索仍使用此前成功的版本。',
    allowTitle:'允许模型使用这份资料？',allowIntro:'相关片段和标题可发送给此范围内获准使用的模型服务商，用于回答和引用。',allowConfirm:'允许使用',allowToast:'已允许模型使用此资料。',revokeTitle:'改为仅本地使用？',revokeIntro:'本地资料及版本会保留。后续模型请求不会再使用此资料。',revokeImpact:'已有回答和思考保留，但相关引用将不可用；受影响的对话内容不再发送给模型。',revokeConfirm:'改为仅本地',revokeToast:'已改为仅本地，相关历史引用已不可用。',
    deleteTitle:'删除这份资料？',deleteIntro:'将删除 Mira 中这份资料的全部版本、片段及相关派生内容。此操作无法撤销。',deleteImpact1:'引用这份资料的相关生成回答与思考也会被清理；原始用户消息保留。',deleteImpact2:'你最初导入的外部文件不会被删除。',deleteConfirm:'删除资料',deleteToast:'资料和相关生成内容已清理。',
    notesTitle:'Knowledge · 设计提案 01',notes1:'<strong>列表与阅读并列。</strong>复用 Mira 侧栏和 Memory 的浏览方式，正文获得主要阅读空间。',notes2:'<strong>权限和版本可见。</strong>当前版本用于检索，历史版本保留引用。导入默认仅本地。',notes3:'<strong>窄窗口逐层进入。</strong>850 × 620 下保留侧栏，从列表进入正文，再返回原位置。',notes4:'<strong>供设计评审。</strong>所有内容与操作均为示例；未接入原生应用、个人资料库或模型。浏览器外观不代表原生 macOS 验收。',notes5:'上方可切换空资料库、历史引用和失败场景。正文语言不随界面切换。',
  },
  en: {
    designTitle:'Knowledge',prototype:'Design proposal · Sample data',scenario:'Preview scenario',theme:'Toggle appearance',language:'Switch interface language',reset:'Reset',notes:'Design notes',
    populated:'Browse sources',emptyScenario:'Empty library',citationScenario:'Historical citation',failureScenario:'Failed import',navigation:'Mira navigation',toggleSidebar:'Toggle sidebar',
    newConversation:'New conversation',memory:'Memory',knowledge:'Knowledge',tasks:'Tasks',workspaces:'Workspaces',inbox:'Inbox',recentConversations:'Recent conversations',settings:'Settings',
    import:'Import sources',sourceList:'Source list',sourcePreview:'Source preview',search:'Search titles or content',scopeFilter:'Filter scope',statusFilter:'Filter status',sort:'Sort',allScopes:'All scopes',allStatuses:'All statuses',ready:'Searchable',localOnly:'Local only',modelUse:'Model use allowed',failed:'Parsing failed',needsAttention:'Needs attention',updateFailed:'Update failed',versionTotal:n=>`${n} versions`,recent:'Recently updated',titleSort:'By title',count:n=>`${n} sources`,hits:n=>`${n} matching sources`,localSnapshots:'Source copies stored on this device',
    document:'Document',versions:'Versions',information:'Source info',current:'Current',historical:'Historical',version:n=>`Version ${n}`,currentVersion:n=>`Version ${n} · Current`,versionLabel:'Select source version',updated:'Updated',imported:'Imported',markdown:'Markdown',readOriginal:'View original',readPreview:'Reading view',back:'Back to sources',close:'Close',cancel:'Cancel',done:'Done',more:'More actions',update:'Update source',delete:'Delete source',permission:'Model use',changePermission:'Change access',
    emptyTitle:'Keep useful sources together',emptyBody:'Import Markdown to read anytime. Allow model use to search and cite it in conversations.',selectSource:'Select a source to start reading',noResults:'No matching sources',noResultsBody:'Try another keyword, scope, or status.',clearFilters:'Clear filters',
    snapshotHint:'Imported snapshot · Original file is not synced',historicalNotice:'You are viewing a historical version. New searches use the current version.',backCurrent:'View current',citationNotice:'This answer cited lines 14–16 of version 1. Updating the source keeps that citation tied to the original text.',citationUnavailable:'This citation is unavailable',citationUnavailableBody:'The source was deleted or its model-use permission was revoked. Its cited text is no longer shown here.',citationTitle:'Citation in conversation',citationConversation:'首版的功能边界',citationQuestion:'首版支持哪些资料格式？',citationAnswer:'首版支持导入 Markdown，并保留资料快照。PDF 和网页快照放在后续版本。',openCitation:'Open cited text',
    versionsHelp:'Each explicit update preserves a version. Existing answer citations stay tied to their original content.',view:'View',successfulUpdate:'Source updated',firstImport:'First import',failedUpdate:'Update failed · Previous version remains current',historyUnchanged:'Historical versions are retained. This view does not restore them as current.',
    scope:'Scope',file:'Original file',size:'File size',parseState:'Parse status',versionCount:'Versions kept',sourceType:'Source type',snapshot:'Imported snapshot',fileAccess:'Access to the original file ended after import. Changes to it do not affect this copy.',localDescription:'Read and search on this device. Excluded from remote model requests.',remoteDescription:'Relevant content can be used in conversations within this scope and sent to currently authorized model providers.',
    importTitle:'Import Markdown sources',importIntro:'Save a searchable local snapshot. The original file is not modified or kept in sync.',chooseSamples:'Choose sample files',dropHint:'Choose one or more Markdown files',formatHint:'.md / .markdown · Up to 10 MB each · 100 files per batch',importScope:'Import to',allowRemote:'Allow models to use these sources',allowRemoteHelp:'Relevant excerpts may be sent to configured, authorized model providers. Off by default.',startImport:'Import 3 sources',importing:'Importing…',sampleHelp:'This prototype uses built-in samples and never reads your files.',importResultTitle:'Import complete',importResultIntro:'1 imported, 1 already exists, and 1 needs attention.',added:'Imported',duplicate:'Already exists',duplicateHelp:'Same scope and content. The existing source was reused.',encodingError:'This file is not valid UTF-8. Save it as UTF-8 and import it again.',viewImported:'View imported source',retry:'Choose another file',sampleNew:'阅读方法.md',sampleDuplicate:'Mira 产品原则.md',sampleBad:'访谈记录.md',importToast:'Source imported for local use only.',
    updateTitle:'Update this source',updateIntro:'Choose an updated Markdown file. Successful updates become searchable; earlier versions and citations are kept.',updateName:'The source name and scope stay unchanged.',chooseUpdate:'Choose updated sample',updateSuccess:'Valid new version',updateFailure:'Simulate encoding error',confirmUpdate:'Update source',updateToast:'New version saved. Earlier citations are unchanged.',updateFailedToast:'Update failed. The current version is unchanged.',failedBody:'The original file is retained, but it could not be parsed into searchable content.',failedNoCurrent:'No readable content yet',failedCurrent:'This update could not be parsed. Searches still use the previous successful version.',
    allowTitle:'Allow models to use this source?',allowIntro:'Relevant excerpts and the title may be sent to authorized model providers within this scope to answer questions and provide citations.',allowConfirm:'Allow model use',allowToast:'Model use is now allowed for this source.',revokeTitle:'Use this source locally only?',revokeIntro:'Local content and versions are kept. Future model requests will not use this source.',revokeImpact:'Existing answers and thinking stay visible, but affected citations become unavailable. Dependent conversation content is excluded from future model requests.',revokeConfirm:'Make local only',revokeToast:'Source is local only. Affected historical citations are unavailable.',
    deleteTitle:'Delete this source?',deleteIntro:'All of this source’s versions, excerpts, and related derived content in Mira will be deleted. This cannot be undone.',deleteImpact1:'Affected generated answers and thinking that depend on this source will also be cleared. Original user messages are kept.',deleteImpact2:'The external file you originally imported will not be deleted.',deleteConfirm:'Delete source',deleteToast:'Source and affected generated content cleared.',
    notesTitle:'Knowledge · Design proposal 01',notes1:'<strong>Browse and read together.</strong>Keep Mira’s sidebar and Memory browsing pattern, with space reserved for the document.',notes2:'<strong>Visible permissions and versions.</strong>Search uses the current version; historical citations stay intact. Imports are local only by default.',notes3:'<strong>Drill in at compact widths.</strong>At 850 × 620, keep the sidebar and return from reading to the same list position.',notes4:'<strong>For design review.</strong>Content and actions are synthetic, without native app, personal library, or model integration. Browser rendering does not establish native macOS acceptance.',notes5:'Use the review controls for empty, historical-citation, and failure scenarios. Document language stays unchanged.',
  }
};
const principleText = [
'# Mira 产品原则', '', '一个能延续上下文的个人 AI 工作空间。对话、记忆与资料各有位置，也能在需要时联系起来。', '',
'## 让资料进入对话', '', '资料是需要完整保留的原始内容。用户可以阅读、搜索，也可以让 Mira 在回答时引用其中的相关段落。', '',
'- 导入后保存一份独立快照，原文件保持不变。', '- 仅在允许模型使用后，相关内容才会进入远程请求。', '- 回答引用具体版本，资料更新后仍能找到当时的原文。', '',
'## 首版范围', '首版支持导入 Markdown，并保留资料快照。', 'PDF 和网页快照放在后续版本。', '不监听文件夹，也不自动同步外部文件。', '',
'## 让控制权清晰可见', '', '每份资料都能查看所属范围、模型使用权限与历史版本。删除前说明影响，避免把“移除资料”和“保留历史回答”混为一谈。', '',
'## 保持阅读安静', '', '界面以系统字体和中性颜色承载内容。操作靠近对象，辅助信息退后一步，让正文保持连续。'
].join('\n');
const initialSources = [
 {id:1,title:'Mira 产品原则',file:'Mira 产品原则.md',scope:'Mira',remote:true,rank:6,date:'09-23',size:'3.2 KB',snippet:'对话、记忆与资料各有位置，也能在需要时联系起来。',current:2,versions:[
   {number:2,date:'2026-09-23 · 10:32',ready:true,text:principleText},
   {number:1,date:'2026-09-19 · 16:08',ready:true,text:principleText.replace('一个能延续上下文的个人 AI 工作空间。对话、记忆与资料各有位置，也能在需要时联系起来。','Mira 是一个以对话为起点的个人 AI 工作空间。资料为回答提供可以追溯的依据。').replace('## 保持阅读安静\n\n界面以系统字体和中性颜色承载内容。操作靠近对象，辅助信息退后一步，让正文保持连续。','## 后续方向\n\n先验证资料检索与引用，再扩展支持的文件类型。')}
 ]},
 {id:2,title:'界面与交互约定',file:'interface-notes.md',scope:'Mira',remote:true,rank:5,date:'09-22',size:'2.4 KB',snippet:'中性配色、系统字体与原生控件。让内容成为界面的重心。',current:1,versions:[{number:1,date:'2026-09-22 · 15:26',ready:true,text:'# 界面与交互约定\n\n界面应当帮助用户找到内容，而不是要求用户先理解实现方式。\n\n## 基础样式\n\n- 使用系统字体，保留清晰的层级。\n- 中性配色，仅在必要时使用语义色。\n- 列表状态、键盘焦点与错误均有明确反馈。\n\n## 浏览方式\n\n列表与正文并列，窄窗口中逐层进入。返回列表时保留筛选与阅读位置。\n\n## 操作反馈\n\n长操作显示进度。发生错误时保留已完成的结果，并说明下一步。'}]},
 {id:3,title:'检索评估笔记',file:'retrieval-notes.md',scope:'Mira',remote:false,rank:4,date:'09-21',size:'1.8 KB',snippet:'用中文短词、混合文本和路径检查资料能否被准确找到。',current:1,versions:[{number:1,date:'2026-09-21 · 09:40',ready:true,text:'# 检索评估笔记\n\n这是一份待整理的评估笔记，暂时只在本地阅读。\n\n## 查询覆盖\n\n- 中文短词与完整短语。\n- 中英文混合的技术说明。\n- 类型名、文件名与路径。\n\n## 判断依据\n\n找到相似词语并不等于找到答案。每条结果都需要保留它来自哪里，以及对应的原文。\n\n## 无结果时\n\n明确显示没有匹配，保留查询条件，让用户决定修改关键词还是继续阅读。'}]},
 {id:4,title:'Reading with a question',file:'reading-with-a-question.md',scope:'Field Notes',remote:false,rank:3,date:'09-20',size:'1.2 KB',snippet:'Start with a question. Keep the source, not just the summary.',current:1,versions:[{number:1,date:'2026-09-20 · 20:15',ready:true,text:'# Reading with a question\n\nStart with a question. Keep the source, not just the summary.\n\n## Before reading\n\nWrite down what you want to understand. A useful question gives the reading session a direction.\n\n## While reading\n\n- Keep a short quotation with its source.\n- Separate the author’s claim from your interpretation.\n- Leave room for uncertainty.\n\n## After reading\n\nReturn to the original question. Note what changed, what is still unclear, and which source is worth revisiting.'}]},
 {id:5,title:'访谈记录',file:'访谈记录.md',scope:'Mira',remote:false,rank:2,date:'09-19',size:'4.6 KB',snippet:'',current:null,versions:[{number:1,date:'2026-09-19 · 11:08',ready:false,text:''}]},
 {id:6,title:'Markdown syntax notes',file:'markdown-syntax.md',scope:'inbox',remote:true,rank:1,date:'09-18',size:'1.5 KB',snippet:'A small reference for headings, lists and code in imported documents.',current:1,versions:[{number:1,date:'2026-09-18 · 08:30',ready:true,text:'# Markdown syntax notes\n\nA small reference for imported documents.\n\n## Headings\n\nUse a clear heading hierarchy. Sections make a long document easier to browse and cite.\n\n## Lists\n\n- Keep each item focused.\n- Use numbering only when order matters.\n- Link each quotation to its original source.\n\n## Code\n\nKeep identifiers such as `KnowledgeSource` verbatim. Avoid wrapping code in translated labels.\n\n## Links\n\nImported links and remote images do not automatically fetch content.'}]}
];
